sudo: required
language: C

services:
  - docker

before_install:
  - docker pull koomietx/grvy-gcc7-test:v1.0
  - docker ps -a
  - export DOCKER_RUN="docker run -v ${TRAVIS_BUILD_DIR}:/home/test/ koomietx/grvy-gcc7-test:v1.0"

script:
  - ${DOCKER_RUN} /bin/bash -l -c "module load boost && ./bootstrap && ./configure && make -j 4 && make check"

notifications:
  email: false