sudo: required
language: C

services:
  - docker

before_install:
  - docker pull koomietx/grvy-gcc7-test:v1.0
  - docker ps -a
  - docker run koomietx/grvy-gcc7-test:v1.0 /bin/bash -c "ls -a"
  - docker run koomietx/grvy-gcc7-test:v1.0 /bin/bash -l -c "module list"
  - export DOCKER_RUN="docker run -v ${TRAVIS_BUILD_DIR}:/home/test/ koomietx/grvy-gcc7-test:v1.0"

script:
  - echo $SHELL
  - uname -a
  - pwd
  - ${DOCKER_RUN} test.sh

notifications:
  email: false