sudo: required
language: C

services:
  - docker

before_install:
  - docker pull koomietx/grvy-gcc7-test:v1.0
  - docker ps -a
#  - docker run koomietx/grvy-gcc7-test:v1.0 /bin/bash -c "ls -a"
#  - docker run koomietx/grvy-gcc7-test:v1.0 /bin/bash -l -c "module list"
  - export DOCKER_RUN="docker run -v ${TRAVIS_BUILD_DIR}:/home/test/ koomietx/grvy-gcc7-test:v1.0"

script:
  - ${DOCKER_RUN} /bin/bash -l -c "ls -ld ."
  - ${DOCKER_RUN} /bin/bash -l -c "ls -la"
  - ${DOCKER_RUN} /bin/bash -l -c "id"
  - ${DOCKER_RUN} /bin/bash -l -c "touch foo"
  - ${DOCKER_RUN} /bin/bash -l -c "./bootstrap"
#  - ${DOCKER_RUN} /bin/bash -c "pwd"
#  - ${DOCKER_RUN} /bin/bash -c "ls -la"
#  - ${DOCKER_RUN} /bin/bash -c "./test.sh"

notifications:
  email: false