sudo: required
language: C

services:
  - docker

before_install:
  - docker pull koomietx/grvy-gcc7-test:v1.0
  - docker ps -a
  - docker run koomietx/grvy-gcc7-test:v1.0 /bin/bash -c "ls -a"

jobs: 
  include:
    - stage: build
    script ./bootstrap

